version: 0.2
phases:
  install:
    commands:
      - pip install awscli
  build:
    commands:
      - echo "Starting SBOM export..."
      - aws inspector2 start-sbom-export \
          --resource-arn arn:aws:ecr:us-east-1:332139984345:repository/hello-inspector \
          --destination s3://my-sbom-storage-sbbadwal/sbom/ \
          --output-format CycloneDx_1_4
